# Jason Laso                                                                #
# 2/8/17                                                                    #
# MAR6646                                                                   #
# Simulation of Multinomial Logit Model Results for ABB Electric Case Study #
# ###########################################################################


# set wd to where data is downloaded and then read it in as x
setwd("C://Users//Jason//Downloads")
x = read.csv(file="Case Analysis 2_Data.csv", sep=",", header=T)

# initialize vector, purch, for simulations where customer converts to our firm (ABB)
x$purch = NA

#initialize new vector to store results of each sim and random number generation
simulation=c()
rand=c()

# set number of iterations for sim
iterations = 10000

#set seed
set.seed(1)

#simulation for revenue generated by marketing campaign
for(i in 1:iterations){
  
  #loop through each row
  for(row in 1:nrow(x)){
    
    #pull a random decimal between 0 and 1 for each row
    rand[row] = sample(seq(1:1000),1)/1000
    
      # compare each's customers prob of conversion to ABB to its random number generated
      if(rand[row] <= x$ABB.Prob[row]){
          x$purch[row] = 1
      } else{
          x$purch[row] = 0
      }
    
  # append sum of total gross revenue generated in the iteration
  simulation[i] = sum(x$Size * x$purch)
  
  #progress tracker
  print(i)
  
  }
}

# save results of the simulation as a df
simulation = as.data.frame(simulation)

#change column name to something more appropriate for graph
colnames(simulation) = c("Revenue.Earned")

# check results of the simulation
summary(simulation$Revenue.Earned)


# Plot density curve for simulation with mean and median
ggplot(simulation, aes(x=Revenue.Earned, y=..density..)) + geom_freqpoly(size=1.5) +
  geom_vline(aes(xintercept=mean(Revenue.Earned)), color="orange", linetype="dashed", size=1.5) +
  geom_vline(aes(xintercept=median(Revenue.Earned)), color="blue", linetype="dashed", size=1.5) +
  ggtitle(label="Distribution of Revenue Earned Using Targeted Marketing Campaign") +
  theme(plot.title = element_text(color="red", face="bold", size=16, hjust=.5)) +
  labs(x="Revenue Earned (in $1000s)")

# How often do we make at least $15M?
prop.table(table(simulation$Revenue.Earned > 15000))


 
# Campaign has an expected value of $6.239M. The median is skewed left at $5.027M due to high concentration of 
# target customers with low probability of conversion (leading to many smaller outcomes). 
# The IQR is between $3.744M and $6.712M.
# The best case scenario is $19.15M, although we only make over $15M 5.91% of the time.